import type { ReviewItem, PushResult, Priority } from "@/lib/types";

const PRIORITY_LABEL: Record<Priority, string> = {
  urgent: "priority/urgent",
  high: "priority/high",
  medium: "priority/medium",
  low: "priority/low",
};

interface GitHubConfig {
  token: string;
  owner: string;
  repo: string;
}

function loadConfig(): GitHubConfig {
  const token = process.env.GITHUB_TOKEN;
  const owner = process.env.GITHUB_OWNER;
  const repo = process.env.GITHUB_REPO;
  if (!token || !owner || !repo) {
    throw new Error(
      "GitHub not configured. Set GITHUB_TOKEN, GITHUB_OWNER, and GITHUB_REPO."
    );
  }
  return { token, owner, repo };
}

function buildBody(item: ReviewItem): string {
  const lines: string[] = [];
  if (item.description) lines.push(item.description, "");
  lines.push("---");
  if (item.source_quote) {
    lines.push("**Source quote**");
    lines.push(`> ${item.source_quote.replace(/\n/g, "\n> ")}`);
    lines.push("");
  }
  lines.push(
    `_Confidence: ${item.confidence.toFixed(2)} · Generated by TicketForge_`
  );
  return lines.join("\n");
}

export async function createGitHubIssues(
  items: ReviewItem[]
): Promise<PushResult[]> {
  const config = loadConfig();
  const results: PushResult[] = [];

  for (const item of items) {
    const labels = [PRIORITY_LABEL[item.priority]];
    if (item.assignee_hint) {
      labels.push(`assignee/${item.assignee_hint.toLowerCase().replace(/\s+/g, "-")}`);
    }

    const res = await fetch(
      `https://api.github.com/repos/${config.owner}/${config.repo}/issues`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${config.token}`,
          Accept: "application/vnd.github+json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          title: item.title,
          body: buildBody(item),
          labels,
        }),
      }
    );

    if (!res.ok) {
      const errorText = await res.text();
      throw new Error(`GitHub API error: ${res.status} ${errorText}`);
    }

    const data = (await res.json()) as { number: number; html_url: string };
    results.push({
      id: item.id,
      identifier: `#${data.number}`,
      url: data.html_url,
      title: item.title,
    });
  }

  return results;
}
