import type { ReviewItem, PushResult, Priority } from "@/lib/types";

const PRIORITY_LABEL: Record<Priority, string> = {
  urgent: "Urgent",
  high: "High",
  medium: "Medium",
  low: "Low",
};

interface NotionConfig {
  token: string;
  databaseId: string;
}

function loadConfig(): NotionConfig {
  const token = process.env.NOTION_TOKEN;
  const databaseId = process.env.NOTION_DATABASE_ID;
  if (!token || !databaseId) {
    throw new Error(
      "Notion not configured. Set NOTION_TOKEN and NOTION_DATABASE_ID."
    );
  }
  return { token, databaseId };
}

function buildChildren(item: ReviewItem) {
  const blocks: object[] = [];

  if (item.description) {
    blocks.push({
      object: "block",
      type: "paragraph",
      paragraph: {
        rich_text: [{ type: "text", text: { content: item.description } }],
      },
    });
  }

  if (item.source_quote) {
    blocks.push({
      object: "block",
      type: "quote",
      quote: {
        rich_text: [{ type: "text", text: { content: item.source_quote } }],
      },
    });
  }

  blocks.push({
    object: "block",
    type: "paragraph",
    paragraph: {
      rich_text: [
        {
          type: "text",
          text: {
            content: `Confidence: ${item.confidence.toFixed(2)} · Generated by TicketForge`,
          },
          annotations: { italic: true, color: "gray" },
        },
      ],
    },
  });

  return blocks;
}

export async function createNotionPages(
  items: ReviewItem[]
): Promise<PushResult[]> {
  const config = loadConfig();
  const results: PushResult[] = [];

  for (const item of items) {
    const properties: Record<string, unknown> = {
      Name: {
        title: [{ type: "text", text: { content: item.title } }],
      },
      Priority: {
        select: { name: PRIORITY_LABEL[item.priority] },
      },
    };

    if (item.assignee_hint) {
      properties.Assignee = {
        rich_text: [{ type: "text", text: { content: item.assignee_hint } }],
      };
    }

    const res = await fetch("https://api.notion.com/v1/pages", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${config.token}`,
        "Notion-Version": "2022-06-28",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        parent: { database_id: config.databaseId },
        properties,
        children: buildChildren(item),
      }),
    });

    if (!res.ok) {
      const errorText = await res.text();
      throw new Error(`Notion API error: ${res.status} ${errorText}`);
    }

    const data = (await res.json()) as { id: string; url: string };
    const shortId = data.id.replace(/-/g, "").slice(-6).toUpperCase();
    results.push({
      id: item.id,
      identifier: `NOT-${shortId}`,
      url: data.url,
      title: item.title,
    });
  }

  return results;
}
